---

# Derived from https://github.com/jamesdmorgan/vagrant-ansible-docker-swarm

- name: Update apt repo
  become: yes
  become_user: root
  shell: >
    apt update

- name: Install required packages
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - netcat
      - nmap
      - htop
      - sysstat
      - python-pip
      - bind9
      - jq
      - curl
  tags:
    - packages

- name: install docker python dependencies
  pip: 
    name: 
      - pyyaml
      - docker-py
  tags:
    - packages
